import client from "./client";
import type { IProfileData } from "../stores/profile";
import type { AxiosResponse } from "axios";

interface ISignOutResponse {
  success: boolean;
}

interface IValidateTokenResponse {
  success: boolean;
  data: IProfileData;
}

// Sign out devise session
export const signOut = async (): Promise<AxiosResponse<ISignOutResponse>> => {
  return await client.delete(`/api/v1/companies/auth/sign_out`);
};

// Validate access-token generated by Rails devise.
// Company and employee both use the same devise access-token mechanism.
export const validateToken = async (
  uid: string,
  client_id: string,
  access_token: string
): Promise<AxiosResponse<IValidateTokenResponse>> => {
  return await client.get("/api/v1/companies/auth/validate_token", {
    headers: {
      "access-token": access_token,
      "token-type": "Bearer",
      client: client_id,
      uid,
    },
  });
};
